Repository mju-likelion/12th-crossover-server-1, pull requests merged in 2024-06, with the labels that each got.

#12 Feature/#9 게시판 기능 구현
  src/main/java/com/mju_lion/letter/LetterApplication.java
  src/main/java/com/mju_lion/letter/controller/AuthController.java
  src/main/java/com/mju_lion/letter/controller/BoardController.java
  src/main/java/com/mju_lion/letter/dto/LoginDto.java
  src/main/java/com/mju_lion/letter/dto/SignupDto.java
  src/main/java/com/mju_lion/letter/dto/request/auth/LoginDto.java
  src/main/java/com/mju_lion/letter/dto/request/auth/SignupDto.java
  src/main/java/com/mju_lion/letter/dto/request/board/BoardCreateDto.java
  src/main/java/com/mju_lion/letter/dto/response/ResponseDto.java
  src/main/java/com/mju_lion/letter/dto/response/board/BoardListResponseData.java
  src/main/java/com/mju_lion/letter/dto/response/board/BoardResponseData.java
  src/main/java/com/mju_lion/letter/entity/BaseEntity.java
  src/main/java/com/mju_lion/letter/entity/UserTerm.java
  src/main/java/com/mju_lion/letter/error/ErrorCode.java
  src/main/java/com/mju_lion/letter/repository/BoardRepository.java
  src/main/java/com/mju_lion/letter/service/AuthService.java
  src/main/java/com/mju_lion/letter/service/BoardService.java
Labels: enhancement

#14 Feature/#13 댓글 기능 구현
  src/main/java/com/mju_lion/letter/authentication/AuthenticationExtractor.java
  src/main/java/com/mju_lion/letter/authentication/AuthenticationInterceptor.java
  src/main/java/com/mju_lion/letter/authentication/JwtTokenProvider.java
  src/main/java/com/mju_lion/letter/controller/AuthController.java
  src/main/java/com/mju_lion/letter/controller/BoardController.java
  src/main/java/com/mju_lion/letter/controller/CommentController.java
  src/main/java/com/mju_lion/letter/dto/request/auth/SigninDto.java
  src/main/java/com/mju_lion/letter/dto/request/comment/CommentCreateDto.java
  src/main/java/com/mju_lion/letter/dto/response/board/BoardResponseData.java
  src/main/java/com/mju_lion/letter/dto/response/comment/CommentListResponseData.java
  src/main/java/com/mju_lion/letter/dto/response/comment/CommentResponseData.java
  src/main/java/com/mju_lion/letter/exception/ConflictException.java
  src/main/java/com/mju_lion/letter/exception/CustomException.java
  src/main/java/com/mju_lion/letter/exception/ForbiddenException.java
  src/main/java/com/mju_lion/letter/exception/NotFoundException.java
  src/main/java/com/mju_lion/letter/exception/UnauthorizedException.java
  src/main/java/com/mju_lion/letter/exception/controller/ExceptionController.java
  src/main/java/com/mju_lion/letter/exception/dto/ErrorResponseDto.java
  src/main/java/com/mju_lion/letter/exception/errorcode/ErrorCode.java
  src/main/java/com/mju_lion/letter/repository/CommentRepository.java
  src/main/java/com/mju_lion/letter/service/AuthService.java
  src/main/java/com/mju_lion/letter/service/BoardService.java
  src/main/java/com/mju_lion/letter/service/CommentService.java
Labels: enhancement

#23 Feature/#22 로직 리팩토링 및 커스텀 예외 수정
  src/main/java/com/mju_lion/letter/controller/TermController.java
  src/main/java/com/mju_lion/letter/exception/errorcode/ErrorCode.java
  src/main/java/com/mju_lion/letter/service/CommentService.java
  src/main/java/com/mju_lion/letter/service/TermService.java
Labels: enhancement, refactoring

#24 Feature/#17 기능 별 주석 작업
  src/main/java/com/mju_lion/letter/service/AuthService.java
  src/main/java/com/mju_lion/letter/service/BoardService.java
  src/main/java/com/mju_lion/letter/service/CommentService.java
  src/main/java/com/mju_lion/letter/service/TermService.java
Labels: documentation

#26 Feature/#25 회원가입 시 이름 중복 검증, 이메일 중복 검증 로직 추가
  src/main/java/com/mju_lion/letter/exception/errorcode/ErrorCode.java
  src/main/java/com/mju_lion/letter/repository/UserRepository.java
  src/main/java/com/mju_lion/letter/service/AuthService.java
Labels: enhancement

#28 Feature/#27 예외 코드 이름 및 메세지 수정
  src/main/java/com/mju_lion/letter/authentication/AuthenticationExtractor.java
  src/main/java/com/mju_lion/letter/authentication/JwtTokenProvider.java
  src/main/java/com/mju_lion/letter/exception/errorcode/ErrorCode.java
  src/main/java/com/mju_lion/letter/service/AuthService.java
Labels: refactoring

#30 Feature/#29 Cors 설정 및 쿠키 sameSite 추가
  src/main/java/com/mju_lion/letter/config/CorsConfig.java
  src/main/java/com/mju_lion/letter/controller/AuthController.java
Labels: enhancement

#32 Feature/#31 commit-message파일 추가
  .gitmessage.txt
Labels: enhancement

#36 Feature/#35 서비스 코드 리팩토링
  src/main/java/com/mju_lion/letter/controller/BoardController.java
  src/main/java/com/mju_lion/letter/controller/CommentController.java
  src/main/java/com/mju_lion/letter/dto/request/page/PaginationData.java
  src/main/java/com/mju_lion/letter/entity/Board.java
  src/main/java/com/mju_lion/letter/entity/Comment.java
  src/main/java/com/mju_lion/letter/service/AuthService.java
  src/main/java/com/mju_lion/letter/service/BoardService.java
  src/main/java/com/mju_lion/letter/service/CommentService.java
Labels: refactoring

#38 Feature/#37 게시물 단건 조회 시 댓글 리스트가 생성시간 오름차순 정렬이 되지않는 문제
  src/main/java/com/mju_lion/letter/repository/CommentRepository.java
  src/main/java/com/mju_lion/letter/service/BoardService.java
Labels: bug, enhancement

#42 Hotfix/#41 댓글있는 게시물은 삭제가 안되는 문제 해결
  src/main/java/com/mju_lion/letter/entity/Board.java
Labels: refactoring

#44 Fix/#43 로그인Dto와 회원가입Dto수정
  src/main/java/com/mju_lion/letter/dto/request/auth/LoginDto.java
  src/main/java/com/mju_lion/letter/dto/request/auth/SigninDto.java
Labels: refactoring

#46 HotFix/#45 SignInDto 약관 필드 검증 추가
  src/main/java/com/mju_lion/letter/dto/request/auth/SigninDto.java
Labels: bug

#48 Hotfix/#47 DtoValidationException, BadRequestException 추가
  src/main/java/com/mju_lion/letter/exception/BadRequestException.java
  src/main/java/com/mju_lion/letter/exception/CustomException.java
  src/main/java/com/mju_lion/letter/exception/DtoValidationException.java
  src/main/java/com/mju_lion/letter/exception/controller/ExceptionController.java
Labels: bug, enhancement

#49 Hotfix#43 Dto 필드에 null 체크 추가
  src/main/java/com/mju_lion/letter/dto/request/auth/LoginDto.java
  src/main/java/com/mju_lion/letter/dto/request/auth/SigninDto.java
Labels: bug, enhancement

#51 Hotfix/#50 Cors Methods 추가
  src/main/java/com/mju_lion/letter/config/CorsConfig.java
Labels: bug, enhancement

#52 Hotfix/#50 cors 설정 변경
  src/main/java/com/mju_lion/letter/config/CorsConfig.java
Labels: bug

#54 Hotfix/#53 약관 Dto 자료형 수정
  src/main/java/com/mju_lion/letter/dto/request/term/TermsAgreementDto.java
  src/main/java/com/mju_lion/letter/exception/dto/ErrorResponseDto.java
  src/main/java/com/mju_lion/letter/service/AuthService.java
Labels: bug
